[theme]
primaryColor = "#F0B308"             
backgroundColor = "#FFFFFF"           
secondaryBackgroundColor = "#ABC6DB"  
textColor = "#0F4883"                 
font = "sans serif"

[secrets]
files = ["/etc/secrets/secrets.toml", ".streamlit/secrets.toml"]
